title: Honest Android Games

menu:
  - label: Home
    url: /
  - label: About
    url: /about/

footer:
  - label: Privacy Policy
    url: /privacy/
  - label: Impress
    url: /impress/
