title: Honest Android Games
language: en-US
description: Endless fun, and you know what you pay for.

menu:
  - label: Home
    url: /
  - label: About
    url: /about/

footer:
  - label: Privacy Policy
    url: /privacy/
  - label: Impress
    url: /impress/
