name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build site
        run: |
          docker run \
            -v ${{ github.workspace }}:/homepage \
            docker.pkg.github.com/ctron/hagen/hagen:latest
